default: &default
  adapter: postgresql

development:
  <<: *default
  database: pig_latin_wikipedia_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: pig_latin_wikipedia_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: pig_latin_wikipedia_production
  username: pig_latin_wikipedia
  password: <%= ENV["ROT13_API_DATABASE_PASSWORD"] %>
  host:     <%= ENV['host'] %>
  port:     <%= ENV['port'] %>
